# Generated by Django 5.0 on 2026-02-11 20:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., USD, EUR)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Full name of the currency",
                        max_length=50,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Currency symbol (e.g., $, €)", max_length=10
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this currency is active in the platform",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valuation_date",
                    models.DateField(
                        db_index=True, help_text="The date for this exchange rate"
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=6,
                        help_text="The exchange rate value",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exchanged_currency",
                    models.ForeignKey(
                        help_text="The target currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates_as_target",
                        to="currencies.currency",
                    ),
                ),
                (
                    "source_currency",
                    models.ForeignKey(
                        help_text="The base currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates_as_source",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency Exchange Rate",
                "verbose_name_plural": "Currency Exchange Rates",
                "ordering": ["-valuation_date", "source_currency__code"],
                "indexes": [
                    models.Index(
                        fields=[
                            "source_currency",
                            "exchanged_currency",
                            "valuation_date",
                        ],
                        name="rate_lookup_idx",
                    ),
                    models.Index(
                        fields=["valuation_date", "source_currency"],
                        name="date_source_idx",
                    ),
                ],
                "unique_together": {
                    ("source_currency", "exchanged_currency", "valuation_date")
                },
            },
        ),
    ]
