# Generated by Django 5.0 on 2026-02-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the provider",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "adapter_path",
                    models.CharField(
                        help_text="Python import path to the adapter class (e.g., 'adapters.currencybeacon.CurrencyBeaconAdapter')",
                        max_length=255,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=100,
                        help_text="Priority order (lower number = higher priority)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this provider is currently active",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific configuration (API keys, endpoints, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exchange Rate Provider",
                "verbose_name_plural": "Exchange Rate Providers",
                "ordering": ["priority", "name"],
            },
        ),
    ]
